{
 "title": "meteo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Station",
    "query": "from(bucket: \"meteo\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meteo\")\n  |> distinct(column: \"Station\")\n  "
   }
  ]
 },
 "panels": [
  {
   "title": "Stations en Haute Garonne",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"meteo\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meteo\")\n  |> filter(fn: (r) =>  r._field == \"LAT\" or r._field == \"LON\")\n  |> pivot(rowKey: [\"Station\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> unique(column: \"Station\")\n  "
    }
   ]
  },
  {
   "title": "Max number of rows received for time range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"meteo\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meteo\")\n  |> count()\n  |> group()\n\n  \n"
    }
   ]
  },
  {
   "title": "Recap: average readings for $station",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"meteo\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meteo\")\n  |> filter(fn: (r) => r.Station == \"${station}\")\n  |> schema.fieldsAsCols()\n  |> drop(columns: [\"LAT\", \"LON\", \"Timestamp\", \"_time\"])\n"
    }
   ]
  },
  {
   "title": "Temperatures for $station",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"meteo\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meteo\")\n  |> filter(fn: (r) => r.Station == \"${station}\")\n  |> filter(fn: (r) => r._field == \"T_min (°C)\" or r._field == \"T_max (°C)\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n\n\n"
    }
   ]
  },
  {
   "title": "Average MIN temperature over time range",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"meteo\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meteo\")\n  |> filter(fn: (r) =>  r._field == \"LAT\" or r._field == \"LON\" or r._field == \"T_min (°C)\")"
    }
   ]
  },
  {
   "title": "Average MIN temperature over time range",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"meteo\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meteo\")\n  |> filter(fn: (r) =>  r._field == \"LAT\" or r._field == \"LON\" or r._field == \"T_max (°C)\")"
    }
   ]
  }
 ]
}